version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
      - "9000:9000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=pvz
      - GIN_MODE=release
    networks:
      - pvz-network
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pvz
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./internal/repository/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - pvz-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:

networks:
  pvz-network:
    driver: bridge 