// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/proto/pvz.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetAllPVZRequest - пустой запрос для получения всех ПВЗ
type GetAllPVZRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllPVZRequest) Reset() {
	*x = GetAllPVZRequest{}
	mi := &file_api_proto_pvz_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllPVZRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllPVZRequest) ProtoMessage() {}

func (x *GetAllPVZRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_pvz_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllPVZRequest.ProtoReflect.Descriptor instead.
func (*GetAllPVZRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_pvz_proto_rawDescGZIP(), []int{0}
}

// GetAllPVZResponse содержит список ПВЗ
type GetAllPVZResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pvzs          []*PVZ                 `protobuf:"bytes,1,rep,name=pvzs,proto3" json:"pvzs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllPVZResponse) Reset() {
	*x = GetAllPVZResponse{}
	mi := &file_api_proto_pvz_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllPVZResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllPVZResponse) ProtoMessage() {}

func (x *GetAllPVZResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_pvz_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllPVZResponse.ProtoReflect.Descriptor instead.
func (*GetAllPVZResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_pvz_proto_rawDescGZIP(), []int{1}
}

func (x *GetAllPVZResponse) GetPvzs() []*PVZ {
	if x != nil {
		return x.Pvzs
	}
	return nil
}

// PVZ представляет пункт выдачи заказов
type PVZ struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	City             string                 `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	RegistrationDate *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=registration_date,json=registrationDate,proto3" json:"registration_date,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PVZ) Reset() {
	*x = PVZ{}
	mi := &file_api_proto_pvz_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PVZ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PVZ) ProtoMessage() {}

func (x *PVZ) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_pvz_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PVZ.ProtoReflect.Descriptor instead.
func (*PVZ) Descriptor() ([]byte, []int) {
	return file_api_proto_pvz_proto_rawDescGZIP(), []int{2}
}

func (x *PVZ) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PVZ) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *PVZ) GetRegistrationDate() *timestamppb.Timestamp {
	if x != nil {
		return x.RegistrationDate
	}
	return nil
}

var File_api_proto_pvz_proto protoreflect.FileDescriptor

const file_api_proto_pvz_proto_rawDesc = "" +
	"\n" +
	"\x13api/proto/pvz.proto\x12\x03pvz\x1a\x1fgoogle/protobuf/timestamp.proto\"\x12\n" +
	"\x10GetAllPVZRequest\"1\n" +
	"\x11GetAllPVZResponse\x12\x1c\n" +
	"\x04pvzs\x18\x01 \x03(\v2\b.pvz.PVZR\x04pvzs\"r\n" +
	"\x03PVZ\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04city\x18\x02 \x01(\tR\x04city\x12G\n" +
	"\x11registration_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x10registrationDate2J\n" +
	"\n" +
	"PVZService\x12<\n" +
	"\tGetAllPVZ\x12\x15.pvz.GetAllPVZRequest\x1a\x16.pvz.GetAllPVZResponse\"\x00B\x1aZ\x18avito-pvz-test/api/protob\x06proto3"

var (
	file_api_proto_pvz_proto_rawDescOnce sync.Once
	file_api_proto_pvz_proto_rawDescData []byte
)

func file_api_proto_pvz_proto_rawDescGZIP() []byte {
	file_api_proto_pvz_proto_rawDescOnce.Do(func() {
		file_api_proto_pvz_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_pvz_proto_rawDesc), len(file_api_proto_pvz_proto_rawDesc)))
	})
	return file_api_proto_pvz_proto_rawDescData
}

var file_api_proto_pvz_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_proto_pvz_proto_goTypes = []any{
	(*GetAllPVZRequest)(nil),      // 0: pvz.GetAllPVZRequest
	(*GetAllPVZResponse)(nil),     // 1: pvz.GetAllPVZResponse
	(*PVZ)(nil),                   // 2: pvz.PVZ
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_api_proto_pvz_proto_depIdxs = []int32{
	2, // 0: pvz.GetAllPVZResponse.pvzs:type_name -> pvz.PVZ
	3, // 1: pvz.PVZ.registration_date:type_name -> google.protobuf.Timestamp
	0, // 2: pvz.PVZService.GetAllPVZ:input_type -> pvz.GetAllPVZRequest
	1, // 3: pvz.PVZService.GetAllPVZ:output_type -> pvz.GetAllPVZResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_proto_pvz_proto_init() }
func file_api_proto_pvz_proto_init() {
	if File_api_proto_pvz_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_pvz_proto_rawDesc), len(file_api_proto_pvz_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_pvz_proto_goTypes,
		DependencyIndexes: file_api_proto_pvz_proto_depIdxs,
		MessageInfos:      file_api_proto_pvz_proto_msgTypes,
	}.Build()
	File_api_proto_pvz_proto = out.File
	file_api_proto_pvz_proto_goTypes = nil
	file_api_proto_pvz_proto_depIdxs = nil
}
